name: sodaverse
channels:
  - defaults
  - conda-forge
dependencies:
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.11.0
  - python=3.9.4
  - pip=20.2.3
  - pip:
    - openai==0.26.0
    - transformers==4.25.1
    - datasets==2.8.0
    - sentencepiece==0.1.97
    - colorful==0.5.5
    - better-exceptions==0.3.3
    - protobuf==3.20.3
    # For linting
    - pylint
    - pycodestyle
    - mypy
